### ISSUE TITLE
failed to run test from wiki

### ISSUE THREAD

**Issue by jenlu** [playingmedia/swish-python#3]
Hi, great work - looking at this and within python / django / ... framework for some integration work right now. Attempted to run test case but get the following issue

```
Python 2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import swish
>>> swish_client = swish.SwishClient(
...     environment=swish.Environment.Test,
...     merchant_swish_number='1231181189',
...     cert=('tests/cert.pem', 'tests/key.pem')
... )
>>> 
>>> payment = swish_client.create_payment(
...     payee_payment_reference='0123456789',
...     callback_url='https://example.com/api/swishcb/paymentrequests',
...     payer_alias='46712345678',
...     amount=100,
...     currency='SEK',
...     message='Kingston USB Flash Drive 8 GB'
... )
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "swish/client.py", line 42, in create_payment
    response = self.post('paymentrequests', payment_request.to_primitive())
  File "swish/client.py", line 24, in post
    verify=self.verify)
  File "xxx/lib/python2.7/site-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "xxx/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "xxx/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "xxx/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "xxx/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:581)
```

**Comment by MadSpindel** [comment]
Hi, and thanks.

I believe this problem is related to the old openssl version on your operating system (OS X). Is it possible to upgrade openssl on your machine? You need newer version with SNI support. Another option is running a VM with Ubuntu on OS X.

One possible solution is installing request with `pip install requests[security]` but(!) I had to disable pyopenssl because it was messing up SSL on Windows 10 and Ubuntu 15.10 with the same error you got. So I disabled it in client.py:

```
try:
    from requests.packages.urllib3.contrib import pyopenssl
    pyopenssl.extract_from_urllib3()
except ImportError:
    pass
```

**Comment by MadSpindel** [comment]
Nevermind, try adding verify=False in SwishClient:
```
import swish

swish_client = swish.SwishClient(
    environment=swish.Environment.Test,
    merchant_swish_number='1231181189',
    cert=('/path/to/cert.pem', '/path/to/key.pem'),
    verify=False
)
```

Or you can use the path to swish.pem:
```
swish_client = swish.SwishClient(
    environment=swish.Environment.Test,
    merchant_swish_number='1231181189',
    cert=('/path/to/cert.pem', '/path/to/key.pem'),
    verify='/path/to/swish.pem'
)
```

**Comment by MadSpindel** [comment]
And btw, the code is not production ready yet. It will be production ready when you can install it with pip install.

**Comment by jenlu** [comment]
Ok, will get up Ubuntu and try it from there, thanks for quick reply! Will get back with how it goes...

**Comment by MadSpindel** [comment]
@jenlu Please try in OS X after adding the verify parameter in SwishClient. I believe it should work on OS X in Python 2.7.9 and newer.

**Comment by MadSpindel** [comment]
I have added a Alpha version to PyPi now. You can install it with pip
`pip install swish`

**Comment by jenlu** [comment]
Ok, got Ubuntu environment up and running now and all works :-)

Got the following warning for Swish certificate - not sure if they are aware of this or if this an issue at all...

` SubjectAltNameWarning: Certificate for mss.swicpc.bankgirot.se has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)`
